import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProvider from '../components/query-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import ContainerComponent from "@/components/base/containerComponent";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< Updated upstream
      <body className={inter.className}>
        <ContainerComponent>{children}</ContainerComponent>
      </body>
=======
      <QueryProvider>
        <body className={inter.className}>{children}</body>
      </QueryProvider>
>>>>>>> Stashed changes
    </html>
  );
}
